PIXYS_VERSION_NUMBER := v2.4

ifndef PIXYS_BUILD_TYPE
PIXYS_BUILD_TYPE := UNOFFICIAL

PRODUCT_GENERIC_PROPERTIES += \
    ro.pixys.buildtype=unofficial
endif

ifeq ($(PIXYS_BUILD_TYPE), OFFICIAL)
PRODUCT_GENERIC_PROPERTIES += \
    ro.pixys.buildtype=official

PRODUCT_PACKAGES += \
    Updater

endif

TARGET_PRODUCT_SHORT := $(subst apixysos_,,$(PIXYS_BUILD))

PIXYS_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)
PIXYS_VERSION := PixysOS-$(PIXYS_VERSION_NUMBER)-$(PIXYS_BUILD)-$(PIXYS_BUILD_DATE)-$(PIXYS_BUILD_TYPE)
PIXYS_MOD_VERSION := PixysOS-$(PIXYS_VERSION_NUMBER)-$(PIXYS_BUILD_DATE)-$(PIXYS_BUILD_TYPE)
PIXYS_FINGERPRINT := PixysOS/$(PIXYS_VERSION_NUMBER)/$(PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(PIXYS_BUILD_DATE)

PRODUCT_GENERIC_PROPERTIES += \
  ro.pixys.version=$(PIXYS_VERSION_NUMBER) \
  ro.pixys.releasetype=$(PIXYS_BUILD_TYPE) \
  ro.modversion=$(PIXYS_MOD_VERSION)

PIXYS_DISPLAY_VERSION := PixysOS-$(PIXYS_VERSION_NUMBER)-$(PIXYS_BUILD)-$(PIXYS_BUILD_TYPE)

PRODUCT_GENERIC_PROPERTIES += \
  ro.pixys.display.version=$(PIXYS_DISPLAY_VERSION)
  ro.pixys.fingerprint=$(PIXYS_FINGERPRINT)
